### ISSUE TITLE
How did u scan the ip?

### ISSUE THREAD

**Issue by tocong282** [sonvirgo/4G-Circumvent#1]
In the vid, i see u using nmap, but what about the subnet, u got it from the ASN or what?

**Comment by sonvirgo** [comment]
> In the vid, i see u using nmap, but what about the subnet, u got it from the ASN or what?

NMAP is useless
NMAP = cheap scan
Just check up or down status
Have to write client to scan using  application protocol 
NMAP cheap scan -> Ip Address down filter ---> Client application protocol scan
Got it?
